---
version: 2

images:
  base_image:
    name: "ghcr.io/ryanmerolle/ansible-runner:stable-2.12"
    signature_required: false
  builder_image:
    name: "ghcr.io/ryanmerolle/ansible-builder:latest"
    signature_required: false

  #ansible_config: 'ansible.cfg'

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  #system: bindep.txt

additional_build_steps:
  append:
    - RUN ansible-galaxy collection install arista.avd -p /usr/share/ansible/collections/ansible_collections
